# Generated by Django 5.2.14 on 2026-05-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resume_ats_score_resume_strength_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_roles',
            field=models.JSONField(default=list),
        ),
    ]
