# Generated by Django 5.2.14 on 2026-05-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_resume_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_text',
            field=models.TextField(default='No Text...'),
        ),
    ]
