# Generated by Django 5.2.14 on 2026-05-30 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_deletedchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.resume'),
        ),
    ]
