# Generated by Django 5.2.14 on 2026-05-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
